blank_issues_enabled: false
contact_links:
  - name: Trabajo de front-end
    url: https://github.community/
    about: Agrega un Screenshot de tu vista y una descripcion
  - name: Trabajo de back-end
    url: https://bounty.github.com/
    about: Agrega una descripción de tu tarea
